fix: comp with share-type property
NervJS/taro-plugin-platform-xhs pull request #9
Opened 2022-08-12 08:12 UTC by Hubmeat

修复小红书平台， button 组件 share-type 场景值的问题

see doc: https://miniapp.xiaohongshu.com/docs/guide/openTransmit

see issue: https://github.com/redengineer/redmini/issues/173

2022-08-12 08:38 UTC, Hubmeat commented
这个 mr，带来的问题就是：用户只能用 share-type 来配置分享场景。这样的话 taro event 里的 dataset 就拿不到分享场景值了，期望用户可以在 taro react 场景里，按照和小红书文档描述一致的方式来配置：<button data-share-type="xx" />

目前看起来实现不了，只能按照 MR 里的方式修改。期望后续 taro 这边可以拓展插件，可通过插件把 data-set 里一些值转成自定义属性，发到“渲染层”。

2022-08-16 06:34 UTC, AdvancedCat requested changes

2022-08-16 06:34 UTC, AdvancedCat commented on rollup.config.js
> +const output = process.env.NODE_ENV === 'development' ? 'dist-dev' : 'dist';
为何要增加 dist-dev 构建目录？

2022-08-16 06:54 UTC, Hubmeat commented on rollup.config.js
> +const output = process.env.NODE_ENV === 'development' ? 'dist-dev' : 'dist';
本地开发的时候，希望可以结合 taro 产物 link 到根目录进行调试。
taro 默认的产物也叫 dist，为了防止文件夹冲突，插件这边就修改成 dist-dev 方便本地调试。

2022-08-16 11:54 UTC, merged